### ISSUE TITLE
Change the way `files` are mapped

### ISSUE THREAD

**Issue by viktor-ku** [viktor-ku/dotthefiles#32]
Right now you have to write this for it to work

```yml
map:
  files:
    - name: .Xresources
      to: ~/
```

I think it would make a lot more sense and a lot less boilerplate code to write this instead:

```yml
map:
  files:
    .Xresources: ~/
```
